"""
rl_policy.py

Generated by train_offline_rl.py.
This file is loaded by the Ryu controller.
"""

Q_TABLE = {'dst_5': {'upper': -10.432039666204947, 'lower': -11.434345200811704}, 'dst_6': {'upper': -11.162750750994299, 'lower': -10.083334919704756}, 'dst_7': {'upper': -11.265605372537818, 'lower': -9.57449233792285}, 'dst_8': {'upper': -12.643645389939241, 'lower': -9.583428899034157}}


def choose_path(src_ip, dst_ip, state=None):
    """
    Choose a path using the offline-trained policy.

    Returns:
        upper -> s1 -> s2 -> s4
        lower -> s1 -> s3 -> s4
    """

    dst_num = int(dst_ip.split(".")[-1])
    key = f"dst_{dst_num}"

    if key in Q_TABLE:
        return max(Q_TABLE[key], key=Q_TABLE[key].get)

    # Fallback behavior
    if dst_num % 2 == 0:
        return "upper"
    return "lower"
