"""
rl_policy.py

Generated by train_offline_rl.py.
This file is loaded by the Ryu controller.
"""

Q_TABLE = {'dst_5': {'upper': -11.864161137486875, 'lower': -11.485063537656396}, 'dst_6': {'upper': -9.928280249349347, 'lower': -13.129811105135817}, 'dst_7': {'upper': -11.53711519603598, 'lower': -11.232176759827087}, 'dst_8': {'upper': -11.176839102252831, 'lower': -11.734407107048321}}


def choose_path(src_ip, dst_ip, state=None):
    """
    Choose a path using the offline-trained policy.

    Returns:
        upper -> s1 -> s2 -> s4
        lower -> s1 -> s3 -> s4
    """

    dst_num = int(dst_ip.split(".")[-1])
    key = f"dst_{dst_num}"

    if key in Q_TABLE:
        return max(Q_TABLE[key], key=Q_TABLE[key].get)

    # Fallback behavior
    if dst_num % 2 == 0:
        return "upper"
    return "lower"
