"""
train_offline_rl.py

Offline RL-style training script for the diamond SDN topology.

This file does NOT run inside Ryu.
It generates a simple policy that chooses between two paths:

upper = s1 -> s2 -> s4
lower = s1 -> s3 -> s4

The trained policy is saved into rl_policy.py.
"""

import random


PATHS = ["upper", "lower"]


def simulate_path_reward(path, traffic_load):
    """
    Simple reward model:
    - lower delay is better
    - lower congestion is better
    """

    if path == "upper":
        base_delay = 5
        congestion = traffic_load["upper"]
    else:
        base_delay = 5
        congestion = traffic_load["lower"]

    reward = -(base_delay + congestion)
    return reward


def train_policy(episodes=500):
    q_table = {}

    for dst in range(5, 9):
        state = f"dst_{dst}"
        q_table[state] = {"upper": 0.0, "lower": 0.0}

    alpha = 0.2
    epsilon = 0.2

    for _ in range(episodes):
        dst = random.randint(5, 8)
        state = f"dst_{dst}"

        traffic_load = {
            "upper": random.randint(1, 10),
            "lower": random.randint(1, 10),
        }

        if random.random() < epsilon:
            action = random.choice(PATHS)
        else:
            action = max(q_table[state], key=q_table[state].get)

        reward = simulate_path_reward(action, traffic_load)

        old_q = q_table[state][action]
        q_table[state][action] = old_q + alpha * (reward - old_q)

    return q_table


def save_policy(q_table, filename="rl_policy.py"):
    with open(filename, "w") as f:
        f.write('"""\n')
        f.write("rl_policy.py\n\n")
        f.write("Generated by train_offline_rl.py.\n")
        f.write("This file is loaded by the Ryu controller.\n")
        f.write('"""\n\n')

        f.write("Q_TABLE = ")
        f.write(repr(q_table))
        f.write("\n\n")

        f.write("""
def choose_path(src_ip, dst_ip, state=None):
    \"\"\"
    Choose a path using the offline-trained policy.

    Returns:
        upper -> s1 -> s2 -> s4
        lower -> s1 -> s3 -> s4
    \"\"\"

    dst_num = int(dst_ip.split(".")[-1])
    key = f"dst_{dst_num}"

    if key in Q_TABLE:
        return max(Q_TABLE[key], key=Q_TABLE[key].get)

    # Fallback behavior
    if dst_num % 2 == 0:
        return "upper"
    return "lower"
""")

    print(f"Saved trained policy to {filename}")


if __name__ == "__main__":
    q_table = train_policy()
    print("Trained Q-table:")
    for state, values in q_table.items():
        print(state, values)

    save_policy(q_table)
